//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrtxIntranetPortal.Company {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class Company {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl htmlable;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(Company target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.CssRegistration @__BuildControl__control2() {
            global::Microsoft.SharePoint.WebControls.CssRegistration @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.CssRegistration();
            @__ctrl.Name = "/_layouts/15/VrtxIntranetStyles/CSS/intranet.css";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlhtmlable() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("ul");
            this.htmlable = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display:none;");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "Expand");
            @__ctrl.ID = "htmlable";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBindinghtmlable);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBindinghtmlable(object sender, System.EventArgs e) {
            System.Web.UI.HtmlControls.HtmlGenericControl dataBindingExpressionBuilderTarget;
            System.Web.UI.Control Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            Container = ((System.Web.UI.Control)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.InnerHtml = global::System.Convert.ToString(Eval("htmlable"), global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::VrtxIntranetPortal.Company.Company @__ctrl) {
            global::Microsoft.SharePoint.WebControls.CssRegistration @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"


<script>



    $(document).ready(function () {        

        var url = window.location.href;
        if (url.indexOf(""ProfileTags"") != -1)
             $("".Expand"").show();       

        $("".expandContent"").click(function () { 
                $("".Expand"").toggle();           
           
        });



        $('.Expand a').each(function () {
            if (url.indexOf(""ProfileTags"") != -1) {
                var linktext = $(this).attr('href');
                if (linktext.search(window.location.search.substring(1)) > -1) {
                    $(this).addClass('list-active');
                }
            }
        });
    });
    


</script>


<div class=""inner-right"">
    <div class=""right-menu-ctr"">
        <div class=""right-menu-header"">IN THIS PAGE</div>
        <ul>
            <li><a href=""../SitePages/Corporate%20Overview.aspx"">Corporate Overview</a></li>
            <li><a href=""../SitePages/Moreceo.aspx"">Message Board</a></li>
            <li><a href=""../SitePages/ManagementDirectories.aspx "">Management Directories</a></li>           
            <li class=""expandContent""><a href=""../SitePages/OdcProfile.aspx"">ODC Service Profiles</a>
                "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlhtmlable();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

            </li>
            <li><a href=""../SitePages/CalendarofCorporateEvents.aspx"">Calendar of Corporate Events</a></li>
            <!--<li><a href=""javascript:void(0)"">Company Newsletter</a></li>  -->
            <li><a href=""../SitePages/ClientTestimonials.aspx"">Client Testimonials</a></li>
        </ul>
        <p><a href=""../SitePages/Archives.aspx?ctype=Company"">
            <img src=""/_layouts/15/VrtxIntranetStyles/Images/archieves.jpg"" width=""244"" height=""38"" /></a></p>

        <p><a href=""/Lists/AskAnExpert/NewForm.aspx?Source=http%3A%2F%2Finhy2012v4%3A5555%2FLists%2FAskAnExpert%2FAllItems%2Easpx%3FInitialTabId%3DRibbon%252EList%26VisibilityContext%3DWSSTabPersistence%23InplviewHashd7fb7cd0-e0d5-4677-99b7-6fc7af3787dd%3D&RootFolder=%2FLists%2FAskAnExpert"">
            <img src=""/_layouts/15/VrtxIntranetStyles/Images/ask-an-expert.jpg"" width=""240"" height=""127"" /></a></p>


    </div>



</div>
"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
