//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDirectory.EmployeeDirectory {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EmployeeDirectory {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EmployeeDirectory target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control2() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ImageUrl = "/_layouts/15/VrtxIntranetStyles/Images/printer-icon.png";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::EmpDirectory.EmployeeDirectory.EmployeeDirectory @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link href=\"../_layouts/15/VrtxIntranetStyles/CSS/jquery.dataTables.css\" rel=\"s" +
                        "tylesheet\" />\r\n\r\n<script src=\"../_layouts/15/VrtxIntranetStyles/JS/jquery.dataTa" +
                        "bles.js\" ></script>\r\n<script src=\"../_layouts/15/EmpDirectory/Empdirectory.js\" >" +
                        "</script>\r\n\r\n<script>\r\n\r\n    function printDiv(printcontent) {\r\n\r\n        var pr" +
                        "intContents = document.getElementById(printcontent).innerHTML;\r\n        var orig" +
                        "inalContents = document.body.innerHTML;\r\n\r\n        document.body.innerHTML = pri" +
                        "ntContents;\r\n        document.getElementById(\'tblEmp_filter\').style.display=\"Non" +
                        "e\";\r\n        window.print();\r\n\r\n        document.body.innerHTML = originalConten" +
                        "ts;\r\n        location.reload();\r\n    }\r\n\r\n   \r\n    function myFunction(printcont" +
                        "ent) {\r\n        \r\n        var contents = document.getElementById(printcontent).i" +
                        "nnerHTML;\r\n        var frame1 = document.createElement(\'iframe\');\r\n        frame" +
                        "1.name = \"frame1\";\r\n        frame1.style.position = \"absolute\";\r\n        frame1." +
                        "style.top = \"-1000000px\";\r\n        document.body.appendChild(frame1);\r\n        v" +
                        "ar frameDoc = frame1.contentWindow ? frame1.contentWindow : frame1.contentDocume" +
                        "nt.document ? frame1.contentDocument.document : frame1.contentDocument;\r\n       " +
                        " frameDoc.document.open();\r\n        frameDoc.document.write(\'<html><head><title>" +
                        "DIV Contents</title>\');\r\n        frameDoc.document.write(\'</head><body>\');\r\n    " +
                        "    frameDoc.document.write(contents);\r\n        frameDoc.document.write(\'</body>" +
                        "</html>\');\r\n        frameDoc.document.close();\r\n        setTimeout(function () {" +
                        "\r\n            window.frames[\"frame1\"].focus();\r\n            window.frames[\"frame" +
                        "1\"].print();\r\n            \r\n            document.body.removeChild(frame1);\r\n    " +
                        "    }, 500);\r\n        return false;\r\n        \r\n        //var printContents = doc" +
                        "ument.getElementById(printcontent).innerHTML;\r\n        //var originalContents = " +
                        "document.body.innerHTML;\r\n\r\n        //document.body.innerHTML = printContents;\r\n" +
                        "        //document.getElementById(\'tblEmp_filter\').style.display = \"None\";\r\n    " +
                        "   \r\n        //window.print();\r\n        //window.location = \"../SitePages/EmpDir" +
                        "ectory.aspx\";\r\n}\r\n\r\n    \r\n    function printReport() {\r\n        var content = \"\"" +
                        ";\r\n        var disp_setting = \"toolbar=no,location=no,directories=yes,menubar=no" +
                        ",\";\r\n        disp_setting += \"scrollbars=yes,width=900, height=600, left=100, to" +
                        "p=25\";\r\n\r\n        soErrorLog = document.getElementById(\"printcontent\").innerHTML" +
                        ";\r\n        content += \"<table \'width=100%\'>\";\r\n        content += \"<tr><td style" +
                        "=\'color:#000000;font-family:tahoma,sans-serif;font-size:10pt;font-weight:bold\'>S" +
                        "O Error LOG</td></tr><tr><td>\" + soErrorLog + \"</td></tr></table>\";\r\n        var" +
                        " docprint = window.open(\"\", \"\", disp_setting);\r\n        docprint.document.open()" +
                        ";\r\n        docprint.document.write(\'<html><head><title>Print</title>\');\r\n       " +
                        " docprint.document.write(\'</head> <body onLoad=\"self.print()\">\');\r\n        docpr" +
                        "int.document.write(content);\r\n        docprint.document.write(\'</body></html>\');" +
                        "\r\n        docprint.document.close();\r\n        docprint.focus();\r\n    }\r\n\r\n    \r\n" +
                        "   \r\n\r\n</script>\r\n\r\n\r\n\r\n\r\n<table style=\"width:100%\" >\r\n    <tr>\r\n        <td>\r\n " +
                        "           <a style=\"padding-left:98%\" onclick=\"printDiv(\'printcontent\')\" >"));
            global::System.Web.UI.WebControls.Image @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\r\n            \r\n        </td>\r\n    </tr>\r\n    <tr >\r\n        <td id=\"tblEmpDe" +
                        "tails\" ></td>\r\n    </tr>\r\n</table>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
